import type { KnowledgeGraph } from "./types";

export const sampleGraph: KnowledgeGraph = {
  positions: [
    {
      id: "standing",
      name: "Standing",
      aliases: ["Neutral standing"],
      description: "Both athletes are standing with no established dominant grip.",
      category: "standing",
      role: "neutral",
      tags: ["entry"],
      x: 80,
      y: 230,
    },
    {
      id: "closed-guard",
      name: "Closed Guard",
      aliases: ["Full guard"],
      description: "Bottom player controls the top player inside a closed leg position.",
      category: "guard",
      role: "bottom",
      tags: ["guard", "fundamental"],
      x: 380,
      y: 80,
    },
    {
      id: "half-guard",
      name: "Half Guard",
      aliases: [],
      description: "Bottom player controls one of the top player's legs.",
      category: "guard",
      role: "bottom",
      tags: ["guard"],
      x: 390,
      y: 370,
    },
    {
      id: "side-control",
      name: "Side Control",
      aliases: ["Side mount"],
      description: "Top player pins the torso while staying perpendicular.",
      category: "control",
      role: "top",
      tags: ["pin", "pressure"],
      x: 710,
      y: 250,
    },
    {
      id: "mount",
      name: "Mount",
      aliases: ["Full mount"],
      description: "Top player controls the torso while straddling the opponent.",
      category: "control",
      role: "top",
      tags: ["control", "scoring"],
      x: 1010,
      y: 100,
    },
    {
      id: "back-control",
      name: "Back Control",
      aliases: ["Back mount"],
      description: "Control behind the opponent with hooks or a body triangle.",
      category: "control",
      role: "top",
      tags: ["control", "submission"],
      x: 1020,
      y: 390,
    },
  ],
  techniques: [
    {
      id: "guard-pull",
      sourcePositionId: "standing",
      targetPositionId: "closed-guard",
      name: "Guard Pull",
      description: "Establish grips, control posture, and sit safely into closed guard.",
      giMode: "both",
      difficulty: "foundation",
      tags: ["entry"],
    },
    {
      id: "single-leg",
      sourcePositionId: "standing",
      targetPositionId: "side-control",
      name: "Single Leg Finish",
      description: "Collect one leg, off-balance, and settle past the knees.",
      giMode: "both",
      difficulty: "foundation",
      tags: ["takedown"],
    },
    {
      id: "knee-cut",
      sourcePositionId: "half-guard",
      targetPositionId: "side-control",
      name: "Knee Cut Pass",
      description: "Win the underhook and clear the trapped knee while controlling the head.",
      giMode: "both",
      difficulty: "intermediate",
      tags: ["pass", "pressure"],
    },
    {
      id: "hip-bump",
      sourcePositionId: "closed-guard",
      targetPositionId: "mount",
      name: "Hip Bump Sweep",
      description: "Sit up, trap the posting arm, and drive the hips through the opponent.",
      giMode: "both",
      difficulty: "foundation",
      tags: ["sweep"],
    },
    {
      id: "elbow-escape",
      sourcePositionId: "mount",
      targetPositionId: "half-guard",
      name: "Elbow Escape",
      description: "Frame, create hip space, and recover one leg at a time.",
      giMode: "both",
      difficulty: "foundation",
      tags: ["escape"],
    },
    {
      id: "chair-sit",
      sourcePositionId: "side-control",
      targetPositionId: "back-control",
      name: "Chair Sit Back Take",
      description: "Expose the near hip, connect seatbelt control, and rotate behind.",
      giMode: "nogi",
      difficulty: "intermediate",
      tags: ["back take"],
    },
    {
      id: "mount-transition",
      sourcePositionId: "side-control",
      targetPositionId: "mount",
      name: "Knee Slide to Mount",
      description: "Isolate the far arm and slide the near knee across the belt line.",
      giMode: "both",
      difficulty: "foundation",
      tags: ["transition"],
    },
  ],
  attachments: [],
};